### ISSUE TITLE
Migrate from socket.io based RCStream to SSE / EventSource based EventStreams

### ISSUE THREAD

**Issue by ottomata** [huggle/XMLRCS#1]
Hiya! WMF plans to decomission the socket.io based RCStream in July this year. We've built a new service called EventStreams that takes its place.

- https://blog.wikimedia.org/2017/03/20/eventstreams/
- https://wikitech.wikimedia.org/wiki/EventStreams

Let us know if there is any way we can help with the switchover.

Thanks!

**Comment by benapetr** [comment]
Is there a working example written in Python or any other sane language that would work on linux and did the same job as RCStream's client?

I want to connect to all streams and keep on fetching all information infinitely, in case that server goes down it should be able to reconnect later and recover the stream.

**Comment by benapetr** [comment]
NVM

I tried the python client example you have on wikitech site and it seems to work, just FYI it's more than 50 times more CPU expensive than old python client for RCStream, but I assume this will not be problem given that it will run on labs and CPU is provided by WMF.

But still the code could probably use some optimization as it utilizes CPU to 90% most of time, or maybe rewrite to C or other low level language, it's unnecessary waste of CPU and electricity (mind the nature!), but yes it seems it can be used

**Comment by ottomata** [comment]
> just FYI it's more than 50 times more CPU expensive than old python client for RCStream

Interesting.  The exact same usage is 50x more CPU intensive?  That is, with RCStream, if you subscribe to all updates, it is 50x less CPU intensive than EventStreams? (which (currently) always subscribes to all updates).

**Comment by ottomata** [comment]
I just did a quick unscientific comparison myself, and I do see much more CPU usage with the python sseclient vs the python socketio_client.  However, when I compare JavaScript EventSource with JavaScript socket.io-client, I see about the same CPU usage.

So, I think there must be something inefficient about this python sseclient library.  I just found https://pypi.python.org/pypi/sseclient-py, perhaps it works better?  I'll try to find some time soon to test it out.

**Comment by ottomata** [comment]
Hm, I just tried sseclient-py with urllib3, and it seems pretty inefficient too.  I couldn't get it to work easily with requests; I kept running into utf-8 decode errors.

**Comment by ottomata** [comment]
Ok, from what I can tell, the main slow down comes with the way the response body is accessed / loaded into memory.  I didn't follow the execution path all the down requests & urllib3 all the way, but, I did notice that I was able to use sseclient-py with urllib3 and have it not use tons of CPU if I do it like:

```
import json
import sseclient

def with_urllib3(url):
    """Get a streaming response for the given event feed using urllib3."""
    import urllib3
    http = urllib3.PoolManager()
    # the .stream(chunk_size) is important here!  Without it, the
    # response body seems to be accessed in an inefficient manner.
    return http.request('GET', url, preload_content=False).stream(1024)

url = 'https://stream.wikimedia.org/v2/stream/recentchange'
response = with_urllib3(url) 

client = sseclient.SSEClient(response)
for event in client.events():
    print('%(user)s edited %(title)s' % json.loads(event.data))
```

This also works better when using sseclient-py with requests, but there is a an decoding but in that library where requests already returns the responses as decoded, and then sseclient-py tries to decode again. 

I'll talk with my team to see what we should do about this (maybe we want to implement our own python-eventsource / sse library?), but for now I'll change just the wikitech python example to the example above.

**Comment by ottomata** [comment]
I submitted a pull request for the sseclient library here: https://bitbucket.org/btubbs/sseclient/pull-requests/12/improve-performance-by-using-iter_content/diff

We'll see...

**Comment by ottomata** [comment]
Ah, they moved to github.  See the mentioned pull request.

**Comment by ottomata** [comment]
Ok, btubbs has merged my recent pull requests.  sseclient should be good to go now.

sseclient 0.18 is now on pip.  https://pypi.python.org/pypi/sseclient/

**Comment by benapetr** [comment]
we actually did this on Vienna hackathon, it's now using event streams
